CREATE TABLE categorie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    parent_id BIGINT,
    CONSTRAINT fk_categorie_parent FOREIGN KEY (parent_id) REFERENCES categorie(id)
);

CREATE TABLE produit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(100) NOT NULL UNIQUE,
    libelle VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    categorie_id BIGINT NOT NULL,
    grade VARCHAR(1) NOT NULL CHECK (grade IN ('A','B','C')),
    prix_ht NUMERIC(10,2) NOT NULL CHECK (prix_ht >= 0),
    taux_tva NUMERIC(4,3) NOT NULL DEFAULT 0.200,
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    garantie_mois INTEGER NOT NULL DEFAULT 12,
    date_ajout TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_produit_categorie FOREIGN KEY (categorie_id) REFERENCES categorie(id)
);
